const free_email_provider_domains = `temporary-email.com
trash-mail.com
inboxbear.com
grr.la
guerillamail.org
tempsky.com
guerrillamail.com
tempinbox.com
mytemp.email
getairmail.com
tempemailco.com
email-unlimited.com
tempmailo.com
tempmail.ninja
getnada.com
instant-email.org
lasersharks.io
tempmailin.com
mailsucker.net
mintemail.com
mailpoof.com
mailsac.com
altmails.com
spam4.me
tempmailaddress.com
luxusmail.org
tempr.email
dropmail.me
trashmail.com
throwawaymail.com
maildrop.cc
mailto.space
10minutemail.com
fakemail.club
adrianminde.com
nameapi.org
mailgutter.com
smailpro.com
tempmailme.com
cs.email
10minutemail.net
tempinbox.xyz
yopmail.com
temporary-mail.net
tempmail.net
freedom.casa
freetempemails.com
mails.tips
fakeinbox.com
mailf5.com
brcreators.com
gmailnator.com
yepmail.co
btemp.com
dispostable.com
tempemail.co
tempail.com
hottempmail.com
moakt.com
tempmail.io
fakemail.net
vanishmail.com
owlymail.com
20minutemail.com
trashspam.com
33mail.com
temp-mail.io
10minutemail.com
20minutemail.com
30minutemail.com
trbvm.com
mailcatch.com
mailinator.com
sharklasers.com
spam4.me
temp-mail.org
yopmail.com
mailnesia.com
guerrillamail.com
getairmail.com
throwawaymail.com
dispostable.com
mytrashmail.com
mintemail.com
spamgourmet.com
emailondeck.com
maildrop.cc
mailexpire.com
mailsac.com
trashmail.com
tempail.com
tempmailaddress.com
mailtemp.info
nospamfor.us
nowmymail.com
mailnull.com
spambox.us
tempmail.de
spamfree24.org
spaml.de
mohmal.com
mailslite.com
nobulk.com
koszmail.pl
tempail.com
10minutemail.net
tempmailaddress.com
mailexpire.com
tempmailbox.net
spamfree24.net
spamfree24.info
spamfree24.de
spamfree24.com`;

export const free_email_provider_set = new Set(free_email_provider_domains.split('\n'));
